ValentinBedague/My_AI_CookBook

app/controllers/users_controller.rb
app/views/collections/index.html.erb
app/views/collections/new.html.erb
app/views/collections/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

rajout du controller user avec la show et rajouts de liens entre les differentes pages

push intermediaire

---

app/controllers/recipes_controller.rb
app/views/recipes/index.html.erb
config/routes.rb

add-recipes-views

---

app/views/collections/index.html.erb
app/views/collections/show.html.erb
app/views/pages/home.html.erb

Link recipes collections

---

app/assets/stylesheets/collections.scss

ajout d'un hover sur les card de books

ajout d'un hover

---

app/assets/stylesheets/_collection.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/views/collections/index.html.erb

reorga scss

---

app/views/collections/index.html.erb
app/views/collections/show.html.erb
app/views/recipes/index.html.erb
app/views/recipes/show.html.erb
app/views/users/show.html.erb

changement des url image

---

app/controllers/recipes_controller.rb
app/models/recipe.rb
app/views/recipes/new_via_img.html.erb
config/initializers/ruby_llm.rb
config/storage.yml
db/migrate/20250612105923_create_active_storage_tables.active_storage.rb
db/schema.rb

Create via img

---

Gemfile
Gemfile.lock
app/controllers/recipes_controller.rb
app/views/recipes/new_via_url.html.erb

Create via url + create via img marchent bien

Create via url

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_headers.scss
app/assets/stylesheets/components/_index.scss
app/views/recipes/new_via_url.html.erb

front create via url done avec tous les nouveaux composants

front create via url done avec tous les nouveaux composants

---

app/assets/stylesheets/components/_navbar.scss
app/views/collections/show.html.erb
app/views/shared/_bottom_navbar.html.erb

navbar ton fonct awesome + start front colelction show

navbar ton fonct awesome + start front colelction show

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/views/shared/_bottom_navbar.html.erb

navbar responsive à la page actuelle

navbar responsive à la page actuelle

---

app/assets/stylesheets/components/_navbar.scss
app/views/pages/home.html.erb
app/views/shared/_bottom_navbar.html.erb

Front collection show

---

app/assets/stylesheets/_collection.scss
app/assets/stylesheets/application.scss
app/controllers/recipes_controller.rb
app/views/collections/index.html.erb

Correction recipe controller group by

Correction recipe controller group by

---

db/seeds.rb

Seed modified user password + img

Seed modified user password + img

---

app/views/collections/show.html.erb

centrage bouton edit

---

app/javascript/controllers/modal_controller.js

correction de bugs

---

app/assets/stylesheets/_collection.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/controllers/collections_controller.rb
app/controllers/recipes_controller.rb
app/views/collections/index.html.erb
app/views/pages/home.html.erb
app/views/recipes/index.html.erb

Added searchbar

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navigation.scss
app/javascript/controllers/create_recipe_controller.js

Rotation +

---

app/assets/stylesheets/components/_button.scss
app/controllers/pages_controller.rb
app/controllers/recipes_controller.rb
app/helpers/application_helper.rb
app/javascript/controllers/favorite_controller.js
app/views/collections/show.html.erb
app/views/recipes/index.html.erb
app/views/recipes/show.html.erb
config/routes.rb
db/migrate/20250618103715_add_isfavorite_to_collections.rb
db/schema.rb

Recipe favorites show & index

---

app/assets/stylesheets/_collection.scss
app/controllers/collections_controller.rb
app/javascript/controllers/favorite_collection_controller.js
app/views/collections/index.html.erb
app/views/collections/show.html.erb
config/routes.rb

adding favorites books

---

app/controllers/collections_controller.rb
app/controllers/recipes_controller.rb
app/views/collections/index.html.erb
app/views/recipes/index.html.erb

Keep search query in the bar

---

app/assets/config/manifest.js

pwa v100000
